# Generated by Django 4.2.30 on 2026-06-09 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TEAM_LEAD', 'Team Lead'), ('CEO', 'CEO'), ('ADMIN', 'Global Admin')], default='EMPLOYEE', help_text='User system clearance role', max_length=20)),
                ('employee_id', models.CharField(help_text='Unique employee identification string', max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar_url', models.CharField(blank=True, help_text='Public S3 / Cloud / Gravatar avatar path', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='The department this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.department')),
                ('organization', models.ForeignKey(help_text='The tenant organization this user is isolation-scoped to', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.organization')),
                ('user', models.OneToOneField(help_text='One-to-One connection to Django Auth User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
