# Generated by Django 4.2.30 on 2026-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True, help_text='Public S3 / Cloud / Gravatar avatar path or base64 image data', null=True),
        ),
    ]
