# Generated by Django 4.2.30 on 2026-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TEAM_LEAD', 'Team Lead'), ('GENERAL_MANAGER', 'General Manager'), ('HR', 'HR'), ('CEO', 'CEO'), ('ADMIN', 'Global Admin')], default='EMPLOYEE', help_text='User system clearance role', max_length=20),
        ),
    ]
