version: '3.8'

services:
  backend:
    build:
      context: ./oms_backend
      dockerfile: Dockerfile
    container_name: oms_backend_prod
    restart: always
    env_file:
      - ./oms_backend/.env
    environment:
      - DEBUG=False
      - DATABASE_URL=sqlite:////app/db/db.sqlite3
    volumes:
      - django_static:/app/staticfiles
      - django_media:/app/media
      - sqlite_data:/app/db

  frontend:
    build:
      context: ./oms_frontend
      dockerfile: Dockerfile
    container_name: oms_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - django_static:/usr/share/nginx/html/static:ro
      - django_media:/usr/share/nginx/html/media:ro

volumes:
  sqlite_data:
  django_static:
  django_media:
