# Generated by Django 4.2.30 on 2026-06-09 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_organizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='e.g. ANNUAL | SICK | MATERNITY', max_length=20)),
                ('default_days_per_year', models.PositiveIntegerField(default=15)),
                ('allow_negative_balance', models.BooleanField(default=False, help_text='Whether company policy allows requesting leave days beyond available balance')),
                ('requires_attachment', models.BooleanField(default=False, help_text="E.g., sick leave > 2 days requires doctor's note upload")),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('working_days_requested', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], max_length=15, null=True)),
                ('reason', models.TextField()),
                ('state', django_fsm.FSMField(default='draft', help_text='Current approval state of the leave request', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate_to', models.ForeignKey(blank=True, help_text='Colleague covering duties during absence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_leaves', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave.leavetype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.organization')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_allocated', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('pending', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('available', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='leave.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('holiday_date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False, help_text='If True, holiday repeats annually (day and month are static)')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Specific calendar year for one-off holidays', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_holidays', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'holiday_date', 'year')},
            },
        ),
    ]
