# Generated by Django 4.2.30 on 2026-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaverequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='gm_approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='gm_approved_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='gm_approved_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tl_approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tl_approved_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tl_approved_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
