# Generated by Django 4.2.30 on 2026-06-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_ceo_approval_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='default_days_per_year',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
