# Generated by Django 4.2.30 on 2026-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0002_alter_pettycashrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashrequest',
            name='ceo_approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='ceo_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='ceo_approved_needed_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='hr_disbursement_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='tl_approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='tl_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='tl_approved_needed_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
