# Generated by Django 4.2.30 on 2026-06-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A Maze Venture | mYnt Connect | Braincount', max_length=100)),
                ('slug', models.CharField(help_text='e.g. amaze | mynt | braincount', max_length=20, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(default='#HEX', max_length=7)),
                ('secondary_color', models.CharField(default='#HEX', max_length=7)),
                ('theme_name', models.CharField(default='amaze', help_text='Theme class corresponding to DaisyUI theme', max_length=20)),
                ('policy_config', models.JSONField(blank=True, default=dict, help_text='Configurable company policies like leave carry-overs and negative leaves.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly budget in BDT (৳)', max_digits=12)),
                ('budget_spent_this_month', models.DecimalField(decimal_places=2, default=0.0, help_text='Running total of spending this month in BDT (৳)', max_digits=12)),
                ('budget_reset_day', models.PositiveIntegerField(default=1, help_text='Day of the month to reset the budget spent to zero')),
                ('tl_approval_limit', models.DecimalField(decimal_places=2, default=10000.0, help_text='Max limit before routing to CEO approval in BDT (৳)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='The organization this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization')),
            ],
        ),
    ]
