# Generated by Django 4.2.30 on 2026-06-09 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_seed_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPROVAL_NEEDED', 'Approval Needed'), ('STATUS_CHANGED', 'Status Changed'), ('DELEGATION_GRANTED', 'Delegation Granted'), ('BUDGET_WARNING', 'Budget Warning')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='Relative frontend route deep link (e.g. /petty-cash/123/)', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. CREATED | SUBMITTED | APPROVED | REJECTED | DISBURSED | CANCELLED', max_length=50)),
                ('target_type', models.CharField(help_text='Name of the model class (e.g. PettyCashRequest | LeaveRequest)', max_length=100)),
                ('target_id', models.PositiveIntegerField(help_text='Primary key of the affected target object')),
                ('old_state', models.CharField(blank=True, max_length=50, null=True)),
                ('new_state', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, help_text='Free text explanation', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra details (e.g. amount, acted_as_delegate, IP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('PETTY_CASH', 'Petty Cash'), ('LEAVE', 'Leave'), ('ALL', 'All Scope')], default='ALL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Must be set to False after OOO end_date passes')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(help_text='Colleague receiving temporary authority', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_delegations', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(help_text='Person going OOO', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_delegations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='core.organization')),
            ],
        ),
    ]
