# Generated by Django 4.2.30 on 2026-06-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_auditlog_approvaldelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='budget_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Budget cycle frequency', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Budget amount in BDT (৳)', max_digits=12),
        ),
    ]
